name: Deploy to WP PROD

on:
  push:
    tags:
      - v*-qa   
jobs:
  
  init:
    environment: qa
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        run: |
          echo "${{ secrets.TEST }}"
